repos:
- repo: https://github.com/psf/black
  rev: 23.3.0
  hooks:
  - id: black
    exclude: "^({{cookiecutter.project_slug}}/)"
- repo: https://github.com/asottile/reorder_python_imports
  rev: v3.9.0
  hooks:
  - id: reorder-python-imports
    args: ["--py37-plus"]
    exclude: "^({{cookiecutter.project_slug}}/)"
- repo: https://github.com/PyCQA/flake8
  rev: 6.0.0
  hooks:
  - id: flake8
    exclude: "^({{cookiecutter.project_slug}}/)"
- repo: https://github.com/codespell-project/codespell
  rev: v2.2.4
  hooks:
  - id: codespell
- repo: https://github.com/pycqa/pydocstyle
  rev: 6.3.0
  hooks:
  - id: pydocstyle
    additional_dependencies: [toml]
    exclude: "^({{cookiecutter.project_slug}}/)"
- repo: local
  hooks:
  - id: mypy
    name: mypy
    entry: mypy
    language: python
    types: [python]
    require_serial: true
    exclude: "^(doc/)|(test/)"
    args: []
    exclude: "^({{cookiecutter.project_slug}}/)"
